# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "News"
url = "news/"
weight = 2

[[main]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3

[[footer_left]]
name = "Home"
url = "/"
weight = 1

[[footer_left]]
name = "News"
url = "news/"
weight = 2

[[footer_left]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3
